name: CI
on:
  push:
    branches: 
      - main
jobs:
  Build_JPI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: --no-daemon jpi
    - uses: actions/upload-artifact@v1
      with:
        name: jpi
        path: build/libs/templating-engine.hpi
